export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";

export const GET_CURRENT_REQUEST = "GET_CURRENT_REQUEST";
export const GET_CURRENT_SUCCESS = "GET_CURRENT_SUCCESS";
export const GET_CURRENT_FAIL = "GET_CURRENT_FAIL";

export const CURRENT_CATEGORY = "CURRENT_CATEGORY";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "CURRENT_CATEGORY";


